### ISSUE TITLE
ct man not parsing well

### ISSUE THREAD

**Issue by JorisPotier** [code-troopers/ct#15]
The result for some ct man {name} is not well handled for some sections of this readme : https://gitlab.com/transport/filbleu-api/blob/master/README.md

For example : 

```
ct man Test
ct man Build
ct man Prp

```

For these commands the output was not as expected.

**Comment by CedricGatay** [comment]
In fact the output of these items is at third level. Should we extract every sublevel and make it available through man ? How should we deal with multiple part 2 with the same name like in the example below:

 ```
# Links
Facilisis dapibus nunc erat torquent habitasse eros mollis elit sed faucibus, aenean consequat gravida placerat pulvinar et mattis dictumst suspendisse at, tellus cubilia nam ad dui phasellus nec dis litora.
## Prp
Sollicitudin porttitor dui etiam pretium commodo cras nullam, condimentum semper vivamus nec leo posuere pulvinar, fringilla mus sociosqu consectetur fames vehicula.

# Build
Lobortis diam donec vivamus tempor scelerisque lacus potenti porttitor, blandit a ante natoque placerat iaculis molestie pretium aptent, arcu vehicula proin habitant fringilla curae porta.
## Prp
Interdum nisi ad natoque diam tellus venenatis, adipiscing luctus eleifend sit cras semper ultricies, nullam amet nunc aliquet velit.
```

Should we output every Prp part if we issue a `ct man prp` (with their "parent" relationship) or the first one ?
